//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Audit.Data.DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AuditEntity> AuditEntities { get; set; }
        public virtual DbSet<AuditItem> AuditItems { get; set; }
        public virtual DbSet<Cell> Cells { get; set; }
        public virtual DbSet<CertificationType> CertificationTypes { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Lookup> Lookups { get; set; }
        public virtual DbSet<Supplier> Suppliers { get; set; }
        public virtual DbSet<AuditFinding> AuditFindings { get; set; }
        public virtual DbSet<Auditor> Auditors { get; set; }
        public virtual DbSet<AuditorContact> AuditorContacts { get; set; }
        public virtual DbSet<LookupType> LookupTypes { get; set; }
        public virtual DbSet<CertificationElement> CertificationElements { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
    }
}
