//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Audit.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auditor
    {
        public Auditor()
        {
            this.Audits = new HashSet<AuditEntity>();
            this.AuditorContacts = new HashSet<AuditorContact>();
        }
    
        public int ID { get; set; }
        public int Name { get; set; }
        public string Tel { get; set; }
        public string Fax { get; set; }
    
        public virtual ICollection<AuditEntity> Audits { get; set; }
        public virtual ICollection<AuditorContact> AuditorContacts { get; set; }
    }
}
