//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Audit.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public abstract partial class AuditEntity
    {
        public AuditEntity()
        {
            this.AuditItems = new HashSet<AuditItem>();
            this.AuditFindings = new HashSet<AuditFinding>();
        }
    
        public int ID { get; set; }
        public string Description { get; set; }
        public string Reference { get; set; }
        public int AuditTypeID { get; set; }
        public int CompanyID { get; set; }
        public bool IsInternal { get; set; }
        public Nullable<int> AuditorID { get; set; }
        public Nullable<int> AuditorContactID { get; set; }
        public Nullable<int> InternalAuditorID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedByID { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public int ModifiedByID { get; set; }
    
        public virtual Lookup Lookup { get; set; }
        public virtual ICollection<AuditItem> AuditItems { get; set; }
        public virtual Auditor Auditor { get; set; }
        public virtual AuditorContact AuditorContact { get; set; }
        public virtual ICollection<AuditFinding> AuditFindings { get; set; }
    }
}
