//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Audit.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditorContact
    {
        public AuditorContact()
        {
            this.Audits = new HashSet<AuditEntity>();
        }
    
        public int ID { get; set; }
        public int AuditorID { get; set; }
        public string FirstName { get; set; }
        public string Surname { get; set; }
        public string Email { get; set; }
        public string Tel { get; set; }
        public string Fax { get; set; }
        public string MobileNumber { get; set; }
        public string Position { get; set; }
    
        public virtual ICollection<AuditEntity> Audits { get; set; }
        public virtual Auditor Auditor { get; set; }
    }
}
