//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Audit.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CertificationType
    {
        public CertificationType()
        {
            this.Suppliers = new HashSet<Supplier>();
            this.CertificationElements = new HashSet<CertificationElement>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Supplier> Suppliers { get; set; }
        public virtual ICollection<CertificationElement> CertificationElements { get; set; }
    }
}
