//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Audit.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CertificationElement
    {
        public CertificationElement()
        {
            this.CertificationElement1 = new HashSet<CertificationElement>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public int CertificationTypeID { get; set; }
        public Nullable<int> ParentID { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<CertificationElement> CertificationElement1 { get; set; }
        public virtual CertificationElement CertificationElement2 { get; set; }
        public virtual CertificationType CertificationType { get; set; }
    }
}
