//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Audit.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.Employee1 = new HashSet<Employee>();
        }
    
        public int ID { get; set; }
        public string Firstname { get; set; }
        public string Surname { get; set; }
        public string Email { get; set; }
        public string TelNo { get; set; }
        public string FaxNo { get; set; }
        public string MobileNo { get; set; }
        public System.DateTime DateEmployed { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<int> SuperiorID { get; set; }
        public Nullable<System.Guid> UserID { get; set; }
        public bool isActive { get; set; }
        public int EmployeeTypeID { get; set; }
    
        public virtual ICollection<Employee> Employee1 { get; set; }
        public virtual Employee Employee2 { get; set; }
        public virtual Lookup Lookup { get; set; }
    }
}
